### ISSUE TITLE
"python" needs to be capitalized on top page

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-python-programming.rst#29]
In the sentence of text on the top page, "python" needs to be capitalized:

https://python-programming.quantecon.org/

**Comment by mmcky** [comment]
hey @jstac do you mean in the small blurb about the site?

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/8263752/78731549-60353d80-7983-11ea-998a-3ddef720d09a.png">
