### ISSUE TITLE
[about_lectures] needs to be updated for new context

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-python-programming.rst#4]
@jstac the `about_lectures` page needs to be updated for the new context. 

Should this page remain?

https://preview.python-programming.quantecon.org/about_lectures.html

**Comment by jstac** [comment]
Hi @mmcky, all of this can go --- be deleted --- except for the credits down the bottom.  

I'm not sure how we can work the credits in but I think that we should find a way to recognize those who don't have commit histories.  Any ideas?  (CC @DrDrij)

**Comment by jstac** [comment]
By the way, @sayaikegawa has been collecting names for people to give credit to.  

@sayaikegawa, could you please collect the names mentioned above and add them to your list?

**Comment by sayaikegawa** [comment]
I understand @jstac . I'll add names in the credit to my list.

**Comment by sayaikegawa** [comment]
Hi @jstac , This is the name list.
[NAMES.xlsx](https://github.com/QuantEcon/lecture-python-programming/files/4316080/NAMES.xlsx)

**Comment by mmcky** [comment]
thanks for capturing the names @sayaikegawa. Would you mind to post that as a overall issue in `lecture-source-py` issues list?
