### ISSUE TITLE
[check] lecture transfers

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-python-programming.rst#6]
Check if lectures have been transferred succesfully and are in line with https://github.com/QuantEcon/lecture-source-py/issues/956

**Comment by najuzilu** [comment]
@mmcky should `search.rst` be deleted?

**Comment by mmcky** [comment]
@DrDrij does the search page generated by `search.rst` support the search feature on the site?

**Comment by DrDrij** [comment]
> @DrDrij does the search page generated by `search.rst` support the search feature on the site?

Yup this page displays the search results from google custom search. When you enter keywords in the header and submit it redirects to this page, and results are displayed.

**Comment by mmcky** [comment]
thanks @DrDrij. @najuzilu it is similar to the `404.rst` file and they are contained in a hidden `toc` in `index_toc.rst`. Can you remove it from the issue on splitting the lecture as it is an infrastructure page.

**Comment by najuzilu** [comment]
Done! I'll close this issue since all lectures have been transferred.
